"""
TEST-037: Credential Encryption Unit Tests

Tests the vault-reference pattern for SharePoint credentials and the
HAR crypto module's encryption/decryption roundtrip.

Tier 1: Unit tests, mocking allowed, <1s timeout.

Key security invariants:
- client_secret and client_id are NEVER stored in the DB config
- Only a vault reference URI (credential_ref) is persisted
- credential_ref format: vault:mingai/{tenant_id}/{service}/{integration_id}
- HAR private keys are encrypted at rest via Fernet (derived from JWT_SECRET_KEY)
- Decrypted private keys are 64 bytes (32-byte seed + 32-byte public)
"""
import base64
import os
import re
import uuid
from unittest.mock import AsyncMock, patch

import pytest
from pydantic import ValidationError


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TEST_JWT_SECRET = "b" * 64
TEST_TENANT_ID = "aaaaaaaa-1111-2222-3333-444444444444"
TEST_INTEGRATION_ID = "bbbbbbbb-5555-6666-7777-888888888888"

CREDENTIAL_REF_PATTERN = re.compile(r"^vault:mingai/[a-f0-9\-]+/[a-z]+/[a-f0-9\-]+$")


# ---------------------------------------------------------------------------
# SharePoint credential_ref tests
# ---------------------------------------------------------------------------


class TestCredentialRefFormat:
    """Validate the vault reference URI format used for SharePoint configs."""

    def test_vault_ref_matches_expected_pattern(self):
        """credential_ref generated by connect_sharepoint follows vault:mingai/{tid}/{svc}/{iid}."""
        vault_ref = f"vault:mingai/{TEST_TENANT_ID}/sharepoint/{TEST_INTEGRATION_ID}"
        assert CREDENTIAL_REF_PATTERN.match(
            vault_ref
        ), f"vault_ref '{vault_ref}' does not match expected pattern"

    def test_vault_ref_rejects_missing_tenant_id(self):
        """A vault ref without tenant_id segment does not match."""
        bad_ref = f"vault:mingai//sharepoint/{TEST_INTEGRATION_ID}"
        assert not CREDENTIAL_REF_PATTERN.match(bad_ref)

    def test_vault_ref_rejects_empty_service(self):
        """A vault ref with empty service segment does not match."""
        bad_ref = f"vault:mingai/{TEST_TENANT_ID}//{TEST_INTEGRATION_ID}"
        assert not CREDENTIAL_REF_PATTERN.match(bad_ref)

    def test_vault_ref_rejects_plain_secret(self):
        """A raw secret string does not match vault ref pattern."""
        raw_secret = "my-super-secret-client-key-12345"
        assert not CREDENTIAL_REF_PATTERN.match(raw_secret)


class TestSharePointConnectStoresVaultRef:
    """Verify that connect_sharepoint stores credential_ref, never raw secrets."""

    def test_config_contains_credential_ref_not_secrets(self):
        """
        The config dict built by connect_sharepoint must contain
        'credential_ref' and must NOT contain 'client_id' or 'client_secret'.
        """
        from app.modules.documents.sharepoint import SharePointConnectRequest

        body = SharePointConnectRequest(
            name="HR SharePoint",
            site_url="https://company.sharepoint.com/sites/hr",
            library_name="Documents",
            client_id="real-client-id",
            client_secret="real-client-secret",
        )

        integration_id = str(uuid.uuid4())
        tenant_id = TEST_TENANT_ID

        # Reproduce the config-building logic from connect_sharepoint
        vault_ref = f"vault:mingai/{tenant_id}/sharepoint/{integration_id}"
        config = {
            "site_url": body.site_url,
            "library_name": body.library_name,
            "credential_ref": vault_ref,
        }

        assert "credential_ref" in config
        assert config["credential_ref"].startswith("vault:")
        assert "client_id" not in config
        assert "client_secret" not in config
        # The raw secret values must not appear anywhere in the config dict
        assert "real-client-id" not in str(config)
        assert "real-client-secret" not in str(config)

    def test_sharepoint_request_schema_requires_client_secret(self):
        """
        SharePointConnectRequest requires client_secret at the API boundary,
        but the route handler must strip it before DB persistence.
        """
        from app.modules.documents.sharepoint import SharePointConnectRequest

        with pytest.raises(ValidationError):
            SharePointConnectRequest(
                name="Test",
                site_url="https://company.sharepoint.com/sites/test",
                library_name="Docs",
                client_id="cid",
                # client_secret omitted -> should fail validation
            )

    def test_sharepoint_request_rejects_http_url(self):
        """site_url must start with https://."""
        from app.modules.documents.sharepoint import SharePointConnectRequest

        with pytest.raises(ValidationError) as exc_info:
            SharePointConnectRequest(
                name="Test",
                site_url="http://insecure.sharepoint.com/sites/test",
                library_name="Docs",
                client_id="cid",
                client_secret="csec",
            )
        assert "https://" in str(exc_info.value)


# ---------------------------------------------------------------------------
# HAR crypto encryption/decryption roundtrip tests
# ---------------------------------------------------------------------------


class TestHARCryptoRoundtrip:
    """Test Ed25519 keypair generation and Fernet encryption/decryption."""

    @pytest.fixture(autouse=True)
    def _set_jwt_secret(self):
        with patch.dict(os.environ, {"JWT_SECRET_KEY": TEST_JWT_SECRET}):
            yield

    def test_generate_keypair_returns_two_strings(self):
        """generate_agent_keypair returns (public_key_b64, encrypted_private_b64)."""
        from app.modules.har.crypto import generate_agent_keypair

        pub, priv_enc = generate_agent_keypair()
        assert isinstance(pub, str)
        assert isinstance(priv_enc, str)
        assert len(pub) > 0
        assert len(priv_enc) > 0

    def test_public_key_is_32_bytes_base64(self):
        """Public key decodes to exactly 32 bytes (Ed25519 raw format)."""
        from app.modules.har.crypto import generate_agent_keypair

        pub, _ = generate_agent_keypair()
        raw = base64.urlsafe_b64decode(
            pub + "=" * (4 - len(pub) % 4) if len(pub) % 4 else pub
        )
        assert len(raw) == 32

    def test_sign_and_verify_roundtrip(self):
        """Sign a payload with the encrypted private key, then verify with public key."""
        from app.modules.har.crypto import (
            generate_agent_keypair,
            sign_payload,
            verify_signature,
        )

        pub, priv_enc = generate_agent_keypair()
        payload = b"test transaction payload"
        signature = sign_payload(priv_enc, payload)

        assert isinstance(signature, str)
        assert verify_signature(pub, payload, signature) is True

    def test_verify_rejects_tampered_payload(self):
        """Verification fails if payload was modified after signing."""
        from app.modules.har.crypto import (
            generate_agent_keypair,
            sign_payload,
            verify_signature,
        )

        pub, priv_enc = generate_agent_keypair()
        payload = b"original payload"
        signature = sign_payload(priv_enc, payload)

        tampered = b"tampered payload"
        assert verify_signature(pub, tampered, signature) is False

    def test_sign_with_empty_key_raises(self):
        """sign_payload raises ValueError for empty private key."""
        from app.modules.har.crypto import sign_payload

        with pytest.raises(ValueError, match="empty"):
            sign_payload("", b"test")

    def test_get_fernet_requires_jwt_secret(self):
        """get_fernet raises ValueError when JWT_SECRET_KEY is not set."""
        from app.modules.har.crypto import get_fernet

        with patch.dict(os.environ, {"JWT_SECRET_KEY": ""}):
            with pytest.raises(ValueError, match="JWT_SECRET_KEY"):
                get_fernet()

    def test_different_jwt_secrets_produce_different_keys(self):
        """Changing JWT_SECRET_KEY produces a different Fernet key (cannot decrypt old data)."""
        from app.modules.har.crypto import generate_agent_keypair, sign_payload

        # Generate with original secret
        pub, priv_enc = generate_agent_keypair()

        # Try to sign with a different JWT_SECRET_KEY
        with patch.dict(os.environ, {"JWT_SECRET_KEY": "c" * 64}):
            with pytest.raises(ValueError, match="decrypt"):
                sign_payload(priv_enc, b"test")


# ---------------------------------------------------------------------------
# DB schema credential_ref column tests
# ---------------------------------------------------------------------------


class TestIntegrationsSchemaCredentialRef:
    """Verify the integrations table schema includes credential_ref."""

    def test_integrations_table_has_credential_ref_column(self):
        """The integrations table definition includes a credential_ref column."""
        from app.core.schema import TABLE_DEFINITIONS

        integrations_def = TABLE_DEFINITIONS["integrations"]
        assert "credential_ref" in integrations_def

    def test_integrations_credential_ref_is_varchar(self):
        """credential_ref column is VARCHAR(500) -- large enough for vault URIs."""
        from app.core.schema import TABLE_DEFINITIONS

        integrations_def = TABLE_DEFINITIONS["integrations"]
        assert "credential_ref VARCHAR(500)" in integrations_def
