"""
ProfileResolver — three-tier LLM profile resolution (TODO-30).

Resolution order for a given (tenant_id, slot):
  Tier 1 — In-memory LRU cache (process-local, TTL=60s)
  Tier 2 — Redis (cross-process, TTL=300s, key: mingai:{tenant_id}:llm_profile)
  Tier 3 — PostgreSQL (source of truth)

DB resolution precedence:
  1. Tenant's explicit llm_profile_id (stored in tenants.llm_profile_id)
  2. Tenant's BYOLLM profile (owner_tenant_id = tenant_id)
  3. Platform default profile (is_platform_default=true, plan eligible)

Feature flag: LLM_PROFILE_SLOT_ROUTING
  When absent or "0" → return None (caller uses env/legacy fallback)
  When "1" → full resolution, return ResolvedProfile

The flag allows gradual rollout: deploy the code, enable per-tenant,
observe, then enable globally.

# ---------------------------------------------------------------------------
# CALL SITE INVENTORY (B0) — InstrumentedLLMClient usages across the backend
# ---------------------------------------------------------------------------
# Generated by grep -rn "InstrumentedLLMClient" src/backend/ and
#   grep -rn "get_openai_client\|get_intent_openai_client\|get_doc_openai_client" src/backend/
#
# InstrumentedLLMClient call sites:
#   app/core/llm/instrumented_client.py      — the client itself (definition)
#   app/modules/chat/ (orchestration service) — slot="chat"  (primary completions)
#   app/modules/chat/embedding.py             — embed() path (excluded from slot routing)
#   app/modules/chat/vector_search.py         — embed() path (excluded from slot routing)
#   app/modules/issues/triage_agent.py        — slot="chat"  (LLM triage classification)
#   app/modules/agents/routes.py              — slot="agent" (agent template execution)
#   app/modules/documents/indexing.py         — embed() path (excluded from slot routing)
#
# Legacy helpers superseded by InstrumentedLLMClient (all removed):
#   get_openai_client / get_intent_openai_client / get_doc_openai_client
#   — these were single-model functions from the pre-library era.
#   — They are NOT present in the current codebase (confirmed by grep).
# ---------------------------------------------------------------------------
"""
from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field
from typing import Optional

import structlog
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.redis_client import build_redis_key, get_redis

logger = structlog.get_logger()

# ---------------------------------------------------------------------------
# Feature flag
# ---------------------------------------------------------------------------

_SLOT_ROUTING_FLAG = "LLM_PROFILE_SLOT_ROUTING"


def _slot_routing_enabled() -> bool:
    """Return True if the slot routing feature flag is enabled."""
    return os.environ.get(_SLOT_ROUTING_FLAG, "0").strip() == "1"


# ---------------------------------------------------------------------------
# Cache config
# ---------------------------------------------------------------------------

_LRU_TTL_SECONDS = 60       # In-process LRU
_REDIS_TTL_SECONDS = 300    # Redis cross-process

# In-process LRU: dict of {cache_key: (expiry_ts, data_dict)}
_lru_cache: dict[str, tuple[float, dict]] = {}
_LRU_MAX_SIZE = 1000


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ResolvedSlot:
    """A fully resolved slot assignment for one slot type."""

    slot: str                          # "chat" | "intent" | "vision" | "agent"
    library_id: Optional[str]          # llm_library entry UUID
    params: dict = field(default_factory=dict)
    traffic_split: list = field(default_factory=list)


@dataclass
class ResolvedProfile:
    """Fully resolved LLM profile for a tenant at a point in time."""

    profile_id: str
    profile_name: str
    owner_tenant_id: Optional[str]     # None = platform profile
    slots: dict[str, ResolvedSlot]     # keyed by slot name
    resolved_at: float = field(default_factory=time.time)

    def get_slot(self, slot: str) -> Optional[ResolvedSlot]:
        return self.slots.get(slot)

    def to_cache_dict(self) -> dict:
        return {
            "profile_id": self.profile_id,
            "profile_name": self.profile_name,
            "owner_tenant_id": self.owner_tenant_id,
            "resolved_at": self.resolved_at,
            "slots": {
                name: {
                    "slot": s.slot,
                    "library_id": s.library_id,
                    "params": s.params,
                    "traffic_split": s.traffic_split,
                }
                for name, s in self.slots.items()
            },
        }

    @classmethod
    def from_cache_dict(cls, data: dict) -> "ResolvedProfile":
        slots = {
            name: ResolvedSlot(
                slot=s["slot"],
                library_id=s.get("library_id"),
                params=s.get("params", {}),
                traffic_split=s.get("traffic_split", []),
            )
            for name, s in data["slots"].items()
        }
        return cls(
            profile_id=data["profile_id"],
            profile_name=data["profile_name"],
            owner_tenant_id=data.get("owner_tenant_id"),
            slots=slots,
            resolved_at=data.get("resolved_at", 0.0),
        )


# ---------------------------------------------------------------------------
# Error classes
# ---------------------------------------------------------------------------


class ProfileResolutionError(Exception):
    """Raised when profile resolution fails for a non-cache reason."""


# ---------------------------------------------------------------------------
# ProfileResolver
# ---------------------------------------------------------------------------


class ProfileResolver:
    """Three-tier LLM profile resolver.

    Callers should instantiate once per application and reuse.
    The resolver is stateless beyond the in-process LRU dict.

    Usage::

        resolver = ProfileResolver()

        # Returns None if flag disabled or no profile configured
        profile = await resolver.resolve(tenant_id, plan, db)
        if profile:
            slot = profile.get_slot("chat")
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def resolve(
        self,
        tenant_id: str,
        plan: str,
        db: AsyncSession,
    ) -> Optional[ResolvedProfile]:
        """Resolve the LLM profile for a tenant.

        Returns None when:
        - Feature flag LLM_PROFILE_SLOT_ROUTING is not enabled
        - No profile is assigned and no platform default exists

        Never raises — on resolution failure, logs a warning and returns None
        so the caller can use the legacy env/config fallback.
        """
        if not _slot_routing_enabled():
            return None

        cache_key = f"llm_profile:{tenant_id}"

        # Tier 1 — in-process LRU
        cached = self._lru_get(cache_key)
        if cached is not None:
            return cached

        # Tier 2 — Redis
        redis_profile = await self._redis_get(tenant_id)
        if redis_profile is not None:
            self._lru_set(cache_key, redis_profile)
            return redis_profile

        # Tier 3 — DB
        try:
            db_profile = await self._db_resolve(tenant_id, plan, db)
        except Exception as exc:
            logger.warning(
                "llm_profile_resolution_failed",
                tenant_id=tenant_id,
                error=str(exc),
            )
            return None

        if db_profile is not None:
            await self._redis_set(tenant_id, db_profile)
            self._lru_set(cache_key, db_profile)

        return db_profile

    async def invalidate(self, tenant_id: str) -> None:
        """Invalidate cached profile for a tenant (both LRU and Redis)."""
        cache_key = f"llm_profile:{tenant_id}"
        _lru_cache.pop(cache_key, None)
        await self._redis_delete(tenant_id)

    async def invalidate_all(self) -> None:
        """Invalidate ALL tenant profile caches.

        Called when a platform-level change (profile update, set-default, deprecate)
        could affect any tenant. Clears the in-process LRU and scans Redis for all
        matching keys.
        """
        # Clear entire in-process LRU (safest approach for platform-wide changes)
        _lru_cache.clear()

        # Scan Redis for all llm_profile keys and delete them
        try:
            redis = get_redis()
            # Pattern: mingai:*:llm_profile
            pattern = build_redis_key("*", "llm_profile")
            cursor = 0
            deleted = 0
            while True:
                cursor, keys = await redis.scan(cursor, match=pattern, count=100)
                if keys:
                    await redis.delete(*keys)
                    deleted += len(keys)
                if cursor == 0:
                    break
            logger.info("llm_profile_cache_invalidate_all", deleted_keys=deleted)
        except Exception as exc:
            logger.warning("llm_profile_cache_invalidate_all_failed", error=str(exc))

    # ------------------------------------------------------------------
    # Tier 1 — In-process LRU
    # ------------------------------------------------------------------

    def _lru_get(self, cache_key: str) -> Optional[ResolvedProfile]:
        entry = _lru_cache.get(cache_key)
        if entry is None:
            return None
        expiry, data = entry
        if time.time() > expiry:
            del _lru_cache[cache_key]
            return None
        return ResolvedProfile.from_cache_dict(data)

    def _lru_set(self, cache_key: str, profile: ResolvedProfile) -> None:
        # Evict oldest entries when at capacity
        if len(_lru_cache) >= _LRU_MAX_SIZE:
            oldest_key = next(iter(_lru_cache))
            del _lru_cache[oldest_key]
        _lru_cache[cache_key] = (time.time() + _LRU_TTL_SECONDS, profile.to_cache_dict())

    # ------------------------------------------------------------------
    # Tier 2 — Redis
    # ------------------------------------------------------------------

    def _redis_key(self, tenant_id: str) -> str:
        return build_redis_key(tenant_id, "llm_profile")

    async def _redis_get(self, tenant_id: str) -> Optional[ResolvedProfile]:
        try:
            redis = get_redis()
            key = self._redis_key(tenant_id)
            raw = await redis.get(key)
            if raw is None:
                return None
            data = json.loads(raw)
            return ResolvedProfile.from_cache_dict(data)
        except Exception as exc:
            logger.debug("llm_profile_redis_get_failed", tenant_id=tenant_id, error=str(exc))
            return None

    async def _redis_set(self, tenant_id: str, profile: ResolvedProfile) -> None:
        try:
            redis = get_redis()
            key = self._redis_key(tenant_id)
            await redis.setex(key, _REDIS_TTL_SECONDS, json.dumps(profile.to_cache_dict()))
        except Exception as exc:
            logger.debug("llm_profile_redis_set_failed", tenant_id=tenant_id, error=str(exc))

    async def _redis_delete(self, tenant_id: str) -> None:
        try:
            redis = get_redis()
            key = self._redis_key(tenant_id)
            await redis.delete(key)
        except Exception as exc:
            logger.debug("llm_profile_redis_delete_failed", tenant_id=tenant_id, error=str(exc))

    # ------------------------------------------------------------------
    # Tier 3 — PostgreSQL
    # ------------------------------------------------------------------

    async def _db_resolve(
        self, tenant_id: str, plan: str, db: AsyncSession
    ) -> Optional[ResolvedProfile]:
        """Resolve via DB using three-level precedence."""

        # Step 1: Check tenant's explicit llm_profile_id assignment.
        # Also fetch plan here so Step 3 uses the real tenant plan even if the
        # caller passed plan="" (e.g. instrumented_client before it knew the plan).
        tenant_row = await db.execute(
            text("SELECT llm_profile_id, plan FROM tenants WHERE id = :tid"),
            {"tid": tenant_id},
        )
        tenant_result = tenant_row.fetchone()
        # Prefer DB-sourced plan over caller-supplied plan (caller may pass "")
        db_plan = (tenant_result[1] or "") if tenant_result else ""
        effective_plan = db_plan if db_plan else plan
        if tenant_result and tenant_result[0]:
            profile = await self._load_profile(str(tenant_result[0]), db)
            if profile:
                logger.debug(
                    "llm_profile_resolved_explicit",
                    tenant_id=tenant_id,
                    profile_id=profile.profile_id,
                )
                return profile

        # Step 2: Check for tenant's own BYOLLM profile
        byollm_row = await db.execute(
            text(
                "SELECT id FROM llm_profiles "
                "WHERE owner_tenant_id = :tid AND status = 'active' "
                "ORDER BY created_at ASC LIMIT 1"
            ),
            {"tid": tenant_id},
        )
        byollm_result = byollm_row.fetchone()
        if byollm_result:
            profile = await self._load_profile(str(byollm_result[0]), db)
            if profile:
                logger.debug(
                    "llm_profile_resolved_byollm",
                    tenant_id=tenant_id,
                    profile_id=profile.profile_id,
                )
                return profile

        # Step 3: Platform default profile (plan-eligible).
        # Uses effective_plan derived from the DB in Step 1 to avoid the
        # empty-string plan bug when callers don't know the tenant's plan.
        default_row = await db.execute(
            text(
                "SELECT id FROM llm_profiles "
                "WHERE owner_tenant_id IS NULL "
                "AND is_platform_default = true "
                "AND status = 'active' "
                "AND (plan_tiers = '{}' OR :plan = ANY(plan_tiers)) "
                "LIMIT 1"
            ),
            {"plan": effective_plan},
        )
        default_result = default_row.fetchone()
        if default_result:
            profile = await self._load_profile(str(default_result[0]), db)
            if profile:
                logger.debug(
                    "llm_profile_resolved_platform_default",
                    tenant_id=tenant_id,
                    profile_id=profile.profile_id,
                )
                return profile

        logger.debug("llm_profile_not_resolved", tenant_id=tenant_id)
        return None

    async def _load_profile(
        self, profile_id: str, db: AsyncSession
    ) -> Optional[ResolvedProfile]:
        """Load a profile row and build a ResolvedProfile."""
        # LEFT JOIN llm_library to verify each slot's library entry is still
        # published. If an entry was deprecated after assignment, nullify that
        # slot rather than silently falling back to env-default.
        result = await db.execute(
            text(
                "SELECT p.id, p.name, p.owner_tenant_id, "
                "p.chat_library_id, p.intent_library_id, p.vision_library_id, p.agent_library_id, "
                "p.chat_params, p.intent_params, p.vision_params, p.agent_params, "
                "p.chat_traffic_split, p.intent_traffic_split, p.vision_traffic_split, p.agent_traffic_split, "
                "lc.status AS chat_lib_status, "
                "li.status AS intent_lib_status, "
                "lv.status AS vision_lib_status, "
                "la.status AS agent_lib_status "
                "FROM llm_profiles p "
                "LEFT JOIN llm_library lc ON lc.id = p.chat_library_id "
                "LEFT JOIN llm_library li ON li.id = p.intent_library_id "
                "LEFT JOIN llm_library lv ON lv.id = p.vision_library_id "
                "LEFT JOIN llm_library la ON la.id = p.agent_library_id "
                "WHERE p.id = :id AND p.status = 'active'"
            ),
            {"id": profile_id},
        )
        row = result.fetchone()
        if row is None:
            return None

        (
            pid, name, owner_tid,
            chat_lib, intent_lib, vision_lib, agent_lib,
            chat_p, intent_p, vision_p, agent_p,
            chat_s, intent_s, vision_s, agent_s,
            chat_lib_status, intent_lib_status, vision_lib_status, agent_lib_status,
        ) = row

        # Nullify any slot whose library entry is no longer published.
        def _guard_lib(lib_id, lib_status: str | None, slot: str):
            if lib_id and lib_status != "published":
                logger.warning(
                    "llm_profile_slot_library_not_published",
                    profile_id=profile_id,
                    slot=slot,
                    library_id=str(lib_id),
                    library_status=lib_status,
                )
                return None
            return lib_id

        chat_lib = _guard_lib(chat_lib, chat_lib_status, "chat")
        intent_lib = _guard_lib(intent_lib, intent_lib_status, "intent")
        vision_lib = _guard_lib(vision_lib, vision_lib_status, "vision")
        agent_lib = _guard_lib(agent_lib, agent_lib_status, "agent")

        def _j(val) -> dict:
            if val is None:
                return {}
            if isinstance(val, str):
                return json.loads(val)
            return val if isinstance(val, dict) else {}

        def _ja(val) -> list:
            if val is None:
                return []
            if isinstance(val, str):
                return json.loads(val)
            return val if isinstance(val, list) else []

        slots = {
            "chat": ResolvedSlot(
                slot="chat",
                library_id=str(chat_lib) if chat_lib else None,
                params=_j(chat_p),
                traffic_split=_ja(chat_s),
            ),
            "intent": ResolvedSlot(
                slot="intent",
                library_id=str(intent_lib) if intent_lib else None,
                params=_j(intent_p),
                traffic_split=_ja(intent_s),
            ),
            "vision": ResolvedSlot(
                slot="vision",
                library_id=str(vision_lib) if vision_lib else None,
                params=_j(vision_p),
                traffic_split=_ja(vision_s),
            ),
            "agent": ResolvedSlot(
                slot="agent",
                library_id=str(agent_lib) if agent_lib else None,
                params=_j(agent_p),
                traffic_split=_ja(agent_s),
            ),
        }

        return ResolvedProfile(
            profile_id=str(pid),
            profile_name=name,
            owner_tenant_id=str(owner_tid) if owner_tid else None,
            slots=slots,
        )
